Time Zone Parameter
energyquantified/eq-python-client pull request #65
Opened 2023-04-21 13:11 UTC by komape

Added the time zone parameter from issue energyquantified/core#233 to the Python SDK.

Closes #64.

2023-05-02 08:49 UTC, jonmd requested changes
Looks good, just minor tweaks are needed.

(I will leave the PR open until the changes are deployed in the API.)

2023-05-02 08:49 UTC, jonmd commented on energyquantified/time/timezone.py
> +            or tz == GAS_DAY
This is the Pythonic way:

```python
return tz in (UTC, CET, WET, EET, TRT, GAS_DAY)
```

2023-05-02 08:49 UTC, jonmd commented on energyquantified/api/base.py
> +            reason=f"Not a valid time zone: '{var}'",
Should probably say:

> Not a **supported** time zone: '...'

as we only support 5 official time zones + the unofficial EU gas zone.

2023-05-02 08:49 UTC, jonmd commented on docs/userguide/timeseries.rst
> +Time Zone Conversion
We do not capitalize the first letters in headers, so this should be "Time zone conversion"

2023-05-02 08:49 UTC, jonmd commented on CHANGELOG.rst
> +- Add time zone conversion.
We usually just put **dev** in here while it's ongoing work:


```
dev
---

**Improvements**

- Add time zone conversion.

2023-05-02 08:49 UTC, jonmd commented on docs/userguide/periods.rst
> +   >>> )
`begin` and `end` parameters are required, so the example should contain them.

2023-05-02 08:49 UTC, jonmd commented on docs/userguide/timeseries.rst
> +   >>> )
`begin` and `end` parameters are required, so the example should contain them.

2023-05-02 08:49 UTC, jonmd commented on docs/userguide/timeseries.rst
> +Use the ``time_zone`` parameter to convert the data to the given time zone:
Adding some text here, or below the example, about the supported time zones in our API makes sense. I know it is described on the terminology page, but repetition does not hurt.

2023-05-02 08:49 UTC, jonmd commented on energyquantified/api/base.py
> +            import pytz
Move `import pytz` to top.

Dynamic imports are generally discouraged in Python, even though they are allowed.

We do it only in the `utils/pandas.py` file because pandas is not a required dependency, so we try to import it and catch import errors on failure.

2023-05-05 08:49 UTC, komape commented
Added the time zone from the JSON response to the model.

2023-05-12 08:24 UTC, jonmd requested changes
It looks like the zone attribute is unnecessary.

Refer to https://github.com/energyquantified/core/pull/251#pullrequestreview-1424016440 for details.

2023-05-16 10:11 UTC, jonmd requested changes
- The SRMC parser sets a `time_zone`, but the variable is no longer there
- I think we should rename `time_zone` to `timezone` everywhere if we end up changing the param name in core

2023-05-16 10:11 UTC, jonmd commented on energyquantified/parser/srmc.py
> +            time_zone=time_zone,
Remove? There is no `time_zone` variable here, as far as I can see.

2023-05-16 10:11 UTC, jonmd commented on energyquantified/parser/srmc.py
> +            time_zone=time_zone,
Remove? There is no `time_zone` variable here, as far as I can see.

2023-05-16 11:33 UTC, komape commented
@jonmd Renamed timezone everywhere and removed the parameter from the SRMC parser.

2023-05-16 14:02 UTC, jonmd approved these changes
👍🏻

2023-05-16 14:44 UTC, merged