Unit Parameter
energyquantified/eq-python-client pull request #70
Opened 2023-05-08 08:46 UTC by komape

Please have a look at https://github.com/energyquantified/eq-python-client/issues/66#issuecomment-1525043630

Closes #66.

2023-05-11 14:48 UTC, jonmd requested changes
Looks great. I would like to have an example or two in `timeseries.rst` on how to use the `unit` parameter when loading data.

2023-05-15 15:39 UTC, komape commented
Rebased branch on master.

2023-05-26 15:40 UTC, komape commented
Rebased on master and resolved conflicts.

2023-09-21 09:01 UTC, fredriksvendsen requested changes
Good work. The feedback is from looking through the pull request as I have not tested the code.

Notes regarding unchanged code (commenting not supported) or stuff in general:

- [x] `Unit` and `denominator` are lost in conversion from periodseries to timeseries ( `Periodseries.to_timeseries()`) 

`Unit`, `denominator` and `contract` are arguments in `Series`, but is missing in docstrings for `Timeseries` and `Periodseries` (which extends `Series`).

- [x] Add `unit`, `denominator` and `contract` in `Timeseries` docstring
- [x] Add `unit`, `denominator` and `contract` in `Periodseries` docstring

`Unit` and `denominator` is added in both `Timeseries.print()` and `Periodseries.print()`. I assume we also want to include those in `.__str__()` as well.

- [x] Add `unit` and `denominator` in `Periodseries.__str__()`
- [ ] Add `unit` and `denominator` in `Timeseries.__str__()`

- [ ] Should `unit` and `denominator` be included in dataframes? (`Timeseries.to_df()`

We have inconsistent string representations. Some objects join items with comma and line shift, others comma only. If data is missing we use `EMPTY`, `(no data)` or nothing at all. Added a few examples below.

Timeseries.__str__:

```python
# Timeseries.__str__()
def __str__(self):
        items = []
        items.append(f"resolution={self.resolution}")
        items.append(f"curve=\"{self.curve}\"")
        if self.instance:
            items.append(f"instance={self.instance}")
        if self.has_scenarios():
            items.append(f"scenario_names={self.scenario_names}")
        if self.has_data():
            items.append(f"begin=\"{self.begin().isoformat(sep=' ')}\"")
            items.append(f"end=\"{self.end().isoformat(sep=' ')}\"")
        else:
            items.append("EMPTY")
        return f"<Timeseries: {', '.join(items)}>"

# SRMC.__str__()
def __str__(self):
        parts = []
        if self.curve:
            parts.append(f"curve={self.curve}")
        if self.contract:
            parts.append(f"contract={self.contract}")
        if self.options:
            parts.append(f"options={self.options}")
        if self.has_ohlc():
            parts.append(f"ohlc={self.ohlc}")
        if self.has_timeseries():
            parts.append(f"timeseries={self.timeseries}")
        if self.has_periodseries():
            parts.append(f"periodseries={self.periodseries}")
        if not parts:
            return f"<SRMC: (no data)>"
        joined = ',\n '.join(parts)
        return f"<SRMC:\n {joined}\n>"

# OHLCList.__str__()
def __str__(self):
    if self.curve:
        return f"<OHLCList: curve=\"{self.curve}\", items={super().__str__()}>"
    else:
        return f"<OHLCList: items={super().__str__()}>"
```

2023-09-21 09:01 UTC, fredriksvendsen commented on energyquantified/api/instances.py
> -            self._add_int(params, "threshold", threshold, min=0)
`threshold` is removed and `unit` is missing

2023-09-21 09:01 UTC, fredriksvendsen commented on energyquantified/data/base.py
> +    ):
Dosctrings for `Timeseries` and `Periodseries` (i.e., models extending base `Series)` does not describe `contract`, `unit`, and `denominator`.

2023-09-21 09:01 UTC, fredriksvendsen commented on energyquantified/data/ohlc.py
> +        return f"<OHLCList:\n {joined}\n>"
Don't swap between using `:` and `=` (e.g., `curve=` and `unit:`). Stick to equals sign, and remove the appending space.

I don't think we want the `(no data)` part in case nothing is set.

I don't know if we want to wrap stuff in quotes (like we do for curve:  `curve=\"{self.curve}\"`) or not. Examples with and without below.

### With quotes

```python
def __str__(self):
    parts = []
    if self.curve:
        parts.append(f"curve=\"{self.curve}\"")
    if self.unit:
        parts.append(f"unit=\"{self.unit}\"")
    if self.denominator:
        parts.append(f"denominator=\"{self.denominator}\"")
    parts.append(f"items={super().__str__()}"
    return (
        f"<OHLCList: "
        f"{', '.join(parts}"
        f">"
    )
```

### Without quotes

```python
def __str__(self):
    parts = []
    if self.curve:
        parts.append(f"curve={self.curve}")
    if self.unit:
        parts.append(f"unit={self.unit}")
    if self.denominator:
        parts.append(f"denominator={self.denominator}")
    parts.append(f"items={super().__str__()}"
    return (
        f"<OHLCList: "
        f"{', '.join(parts}"
        f">"
    )
```

2023-09-21 09:01 UTC, fredriksvendsen commented on docs/userguide/timeseries.rst
> +
Could include an example _without_ the unit parameter, so that users can see the difference in values.

2023-09-21 09:01 UTC, fredriksvendsen commented on docs/userguide/periods.rst
> +
Could include an example _without_ unit conversion, so that users can see the difference in values.

2023-09-21 09:01 UTC, fredriksvendsen commented on energyquantified/data/periodseries.py
> +              file=file)
Do we want `unit` and `denominator`in the same `print`?

2023-09-21 09:01 UTC, fredriksvendsen commented on energyquantified/data/srmc.py
> +            parts.append(f"denominator: {self.denominator}")
- [x] Change `unit:` to `unit=` (and no space after `=`).
- [x] Change `denominator:` to `denominator=` (and no space after `=`).

2023-09-21 09:01 UTC, fredriksvendsen commented on energyquantified/data/timeseries.py
> +              file=file)
Do we want `unit` and `denominator`in the same `print`?

2023-09-21 09:02 UTC, fredriksvendsen commented on energyquantified/data/base.py
> +    ):
Resolving as this is replaced by a task in the review summary.

2023-09-21 09:32 UTC, komape commented on energyquantified/data/ohlc.py
> +        return f"<OHLCList:\n {joined}\n>"
I can't a

> I don't know if we want to wrap stuff in quotes (like we do for curve: `curve=\"{self.curve}\"`) or not.

I would add them as they are used elsewhere.

2023-09-21 09:35 UTC, komape commented on docs/userguide/timeseries.rst
> +
This section is particularly about units. Non-unit examples are above. I would not add another example here.

2023-09-21 09:35 UTC, komape commented on docs/userguide/periods.rst
> +
This section is particularly about units. Non-unit examples are above. I would not add another example here.

2023-09-21 09:38 UTC, komape commented
> * Should `unit` and `denominator` be included in dataframes? (`Timeseries.to_df()`

How would you add them?

2023-09-22 13:45 UTC, fredriksvendsen commented on docs/userguide/timeseries.rst
> +
> The response data is converted:
> 
>    >>> timeseries.data
>    [<Value: date=2020-01-01 00:00:00+01:00, value=6.39>,
>     <Value: date=2020-01-01 00:15:00+01:00, value=6.38>,
>     <Value: date=2020-01-01 00:30:00+01:00, value=6.64>
>     ...

Data shown in the example does not include the unit, so users cannot know if the values (e.g., 6.39) are in MWh/h or GWh/h. Instead of printing data only, we could print the timeseries object to let users know where the unit is specified.

2023-09-22 13:46 UTC, fredriksvendsen commented on docs/userguide/periods.rst
> +
> The response data is converted:
> 
>    >>> periodseries.data[:3]
>    [<Period: begin=2020-01-01 00:00:00+01:00, end=2020-01-06 00:00:00+01:00, value=60.65.>,
>     <Period: begin=2020-01-06 00:00:00+01:00, end=2020-01-13 00:00:00+01:00, value=60.69>,
>     <Period: begin=2020-01-13 00:00:00+01:00, end=2020-01-20 00:00:00+01:00, value=60.83>]

Data shown in the example does not include the unit, so users cannot know if the values (e.g., 60.65) are in MW or GWh. Instead of printing data only, we could print the periodseries object to let users know where the unit is specified.

2023-09-22 14:00 UTC, fredriksvendsen commented
> > * Should `unit` and `denominator` be included in dataframes? (`Timeseries.to_df()`
> 
> How would you add them?

I don't know if we want to add it, but I think it makes sense considering we include curve names (which includes unit pre-conversion)  in the columns.

One option to include the unit is to append it to `name` in `Timeseriesto_dataframe()`. That way we don't have to change each of the different dataframe methods (e.g., `_timeseries_to_dataframe_value_single_header`, `_timeseries_to_dataframe_scenarios`).

```python
if name is None:
        name = timeseries.name
        include_instance = True
    else:
        include_instance = False
if timeseries.unit is not None:
    name = f"{name}, unit: {timeseries.unit}"
    # If denominator can be set while unit is not, tab the statement below one step out
    if timeseries.denominator is not None:
        name = f"{name}, denominator: {timeseries.denominator}"
```

@jonmd What do you think?

2023-09-25 09:37 UTC, komape commented on docs/userguide/timeseries.rst
> +
I think if we make clear just above the output that we add `GWh/h` as `unit` parameter and that this results in the data being presented as GWh/h. I would expect that users understand this.

Or do you want to have the unit as output in general?

2023-09-25 09:37 UTC, komape commented on docs/userguide/periods.rst
> +
https://github.com/energyquantified/eq-python-client/pull/70#discussion_r1335640162

2023-10-04 07:22 UTC, komape commented on docs/userguide/timeseries.rst
> +
Just print `timeseries.str`.

2023-10-04 07:23 UTC, komape commented on docs/userguide/periods.rst
> +
Just print `str(timeseries)`.

2023-10-04 07:23 UTC, komape commented on docs/userguide/periods.rst
> +
The response data is converted: -> The response data is converted to GW:

2023-10-04 07:24 UTC, komape commented on docs/userguide/timeseries.rst
> +
The response data is converted: -> The response data is converted to GWh/h:

2023-10-06 13:13 UTC, fredriksvendsen reviewed
Looks good, just added my .02 on how we want to present data when describing unit conversion.

@komape @jonmd 
If you guys prefer it the current way the consider it approved :+1:

2023-10-06 13:13 UTC, fredriksvendsen commented on docs/userguide/periods.rst
> +      unit="GW">
Since we include the data in the normal example, I think it makes sense to also include it here just to make it extremely clear that the data is changed.

Suggested change:
```
The response data is converted to `GW`, and the unit is found at the ``unit`` attribute of the series:

   >>> periodseries.data[:3]
   [<Period: begin=2020-01-01 00:00:00+01:00, end=2020-01-06 00:00:00+01:00, value=60.65.>,
    <Period: begin=2020-01-06 00:00:00+01:00, end=2020-01-13 00:00:00+01:00, value=60.69>,
    <Period: begin=2020-01-13 00:00:00+01:00, end=2020-01-20 00:00:00+01:00, value=60.83>]

   >>> str(periodseries)
   <Periodseries:
      resolution=<Resolution: frequency=NONE, timezone=CET>,
      curve="DE Wind Power Installed MW Capacity",
      begin="2020-01-01 00:00:00+02:00",
      end="2023-06-01 00:00:00+02:00",
      unit="GW">
```

2023-10-06 13:13 UTC, fredriksvendsen commented on docs/userguide/timeseries.rst
> +      unit="GWh/h">
Since we include the data in the normal example, I think it makes sense to also include it here just to make it extremely clear that the data is changed.

Suggested change:
```
The response data is converted to `GWH/h`, and the unit is found at the ``unit`` attribute of the series:

   >>> timeseries.data
   [<Value: date=2020-01-01 00:00:00+01:00, value=6.39>,
    <Value: date=2020-01-01 00:15:00+01:00, value=6.38>,
    <Value: date=2020-01-01 00:30:00+01:00, value=6.64>

   >>> str(timeseries)
   <Timeseries: 
      resolution=<Resolution: frequency=P1D, timezone=CET>, 
      curve="DE Wind Power Production MWh/h 15min Actual", 
      begin="2020-01-06 00:00:00+02:00", 
      end="2020-01-06 00:00:00+02:00",
      unit="GWh/h">
```

2023-10-06 13:21 UTC, merged