#61 Add subscription information to curve
energyquantified/eq-python-client pull request #92
Opened 2023-10-10 14:34 UTC by komape

Closes #61

2023-10-11 11:45 UTC, fredriksvendsen requested changes
- [x] Export new subscription models in energyquantified.metadata (see `exporting classes` described below)
- [ ] Describe `Subscription` in `docs/reference/packages.rst` in the `energyquantified.metadata` section.  Briefly mention the different models `SubscriptionAccess`, `SubscriptionCollectionPerm`, and `SubscriptionType`. If subscription is **only** related to `Curve` I think it makes sense to describe it under the `Curve` bulletpoint, otherwise add a new bullet point.
- [ ] Add `Subscription`, `SubscriptionAccess`, `SubscriptionCollectionPerm` and `SubscriptionType` in `docs/reference/reference.rst`
- [ ] Update CHANGELOG.rst
- [ ] Add subscription in string representation of `Curve` (see `Curve.__str__()` below)
- [ ] Breifly mention that curve's include subscription information under the `Curve search` section in `docs.userguide.metadata.rst`
- [ ] Describe the subscription object under the `Curve` section in `docs.userguide.terminology.rst`

## Exporting classes

Import in `energyquantified.metadata.__init__.py`:

```python
from .subscription import (
    Subscription,
    SubscriptionAccess,
    SubscriptionCollectionPerm,
    SubscriptionType,
)
```
This makes it so users can import `Subscription` like this:

`from energyquantified.metadata import Subscription`


And add in `_all_` in the same file:

```python
__all__ = [
    # ...
    # Subscription
    "Subscription",
    "SubscriptionAccess",
    "SubscriptionCollectionPerm",
    "SubscriptionType",
]
```

The `_all_` is used for when users want to import everything:

`from energyquantified.metadata import *`

## Curve.__str__()

NOTE: Await response on the questions below before doing changes.

I just noticed that `Curve.__str__()` only returns `self.name`, unlike `Curve.__repr__()`.
Add subscription in `__repr__`:

```python
def __repr__(self):
    return (
        f"<Curve: \"{self.name}\, "
        f"curve_type={self.curve_type}, "
        f"subscription={self.subscription}>"
    )
```

Question: Use `subscription={self.subscription}` or `subscription={self.subscription.access}`?

Question: We usually define string representations in `__str__()`, and define `__repr__()` to return `self.__str__()`. Do we want to change to this for `Curve`, or keep as is?

 @jonmd  please see the two questions above.

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/metadata/subscription.py
> +        _access_lookup[tag.upper()] = self
Change to lower()

```python
_access_lookup[tag.lower()] = self
```

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/metadata/subscription.py
> +        return f"<Access: \"{self.tag}\">"
Change `<Access ..` to `<SubscriptionAccess ..`.
We usually define the str in `__str__()` and make `__repr__()` invoke `self.__str__()`


```python
def __str__(self):
    return f"<SubscriptionAccess: {self.tag}>"

def __repr__(self):
    return self.__str__()
```

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/metadata/subscription.py
> +        return tag.lower() in _access_lookup[tag.upper()]
Line 89 should be:

```python
return tag.lower() in _access_lookup
```

_Assuming self is stored in \_access_lookup at key in lower._

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/metadata/subscription.py
> +        return _access_lookup[tag.upper()]
Get by tag in lower.

```python
return _access_lookup[tag.lower()]
```

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/metadata/subscription.py
> +        return f"<Subscription: \"{self.label}\", access={self.access}, type={self.type}>"
Move the string representation into `__str__()` and change `__repr__()` to simply returning `self.__str__()`.

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/metadata/subscription.py
> +        return f"<Type: \"{self.tag}\">"
- [ ] Move string representation into `__str__()` and make `__repr__()` return `self.__str__()`
- [ ] Change from "<Type: .." to "<SubscriptionType: .."

```python
def __str__(self):
    return f"<SubscriptionType: {self.tag}>"

def __repr__(self):
    return self.__str__()
```

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/metadata/subscription.py
> +        return f"<CollectionPerm: \"{self.tag}\">"
- [ ] Move string representation into `__str__()` and make `__repr__()` return `self.__str__()`
- [ ] Change from "<CollectonPerm: .." to "<SubscriptionCollectionPerm: .."

```python
def __str__(self):
    return f"<SubscriptionCollectionPerm: {self.tag}>"

def __repr__(self):
    return self.__str__()
```

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/metadata/curve.py
> +        #: The subscription for this curve, :py:class:`Subscription`.
#: The subscription for this curve, :py:class:`Subscription

Add "see":

#: The subscription for this curve, see :py:class:`Subscription

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/parser/metadata.py
> +
Remove blank line at 200.

2023-10-11 11:45 UTC, fredriksvendsen commented on energyquantified/parser/metadata.py
> +from ..metadata.subscription import SubscriptionAccess, SubscriptionType, Subscription, SubscriptionCollectionPerm
Import from metadata (after subscription models exported in `energyquantified.metadata.__init__.py`, described in review comment)

```python
from ..metadata import (
    Subscription,
    SubscriptionAccess,
    SubscriptionType,
    SubscriptionCollectionPerm,
)
```

2023-10-11 12:05 UTC, komape commented on energyquantified/metadata/subscription.py
> +        _access_lookup[tag.upper()] = self
But all the tags are uppercase. Don't we have to use `upper()` then?

2023-10-11 12:06 UTC, komape commented on energyquantified/metadata/subscription.py
> +        return tag.lower() in _access_lookup[tag.upper()]
See https://github.com/energyquantified/eq-python-client/pull/92#discussion_r1354861331

2023-10-11 12:06 UTC, komape commented on energyquantified/metadata/subscription.py
> +        return _access_lookup[tag.upper()]
See https://github.com/energyquantified/eq-python-client/pull/92#discussion_r1354861331

2023-10-17 07:45 UTC, jonmd commented on energyquantified/metadata/subscription.py
> +        return tag.lower() in _access_lookup[tag.upper()]
We always convert to lowercase for lookups elsewhere in the code. So we should also do it here for consistency.

Also, @fredriksvendsen's comment above is relevant. Remove the index thing after `_access_lookup`:

```python
# Wrong
return tag.lower() in _access_lookup[tag.upper()]
# Correct
return tag.lower() in _access_lookup
```

2023-10-17 08:06 UTC, jonmd commented on energyquantified/metadata/subscription.py
> +        return _access_lookup[tag.upper()]
See https://github.com/energyquantified/eq-python-client/pull/92#discussion_r1361660547

2023-10-17 08:25 UTC, fredriksvendsen commented on energyquantified/parser/metadata.py
> +from ..metadata.subscription import SubscriptionAccess, SubscriptionType, Subscription, SubscriptionCollectionPerm
Not fixed

2023-10-17 08:26 UTC, jonmd commented on energyquantified/metadata/curve.py
> +               f"subscription={self.subscription}>"
The current code prints something like:

```
<Curve: "DE Biomass Power Production MWh/h 15min Actual", curve_type=TIMESERIES, subscription=Power – Germany>
```

We want it to be. Whether you have `FREEMIUM`, `TRIAL`, `PAYING` or `BLOCKED` is the most important information in the `repr` on the `Curve` object:

```
<Curve: "DE Biomass Power Production MWh/h 15min Actual", curve_type=TIMESERIES, subscription=TRIAL>
```

2023-10-17 08:32 UTC, fredriksvendsen commented on docs/reference/packages.rst
> +
Add a line shift between bullet points

2023-10-17 08:33 UTC, fredriksvendsen commented on docs/userguide/terminology.rst
> +
Add a blank line (two blank lines between sections)

2023-10-17 11:34 UTC, jonmd approved these changes

2023-10-17 11:37 UTC, merged